spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/racingSettings
    username: racingSettings
    password: 123456
    driver-class-name: org.postgresql.Driver
  mail:
    username:
    password:
    host:
    port: 25
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      password:
  config:
    name: HomeofeSportsRacingSimulatorSettings
server:
  port: 8080



