spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/racingSettings
    username: racingSettings
    password: 123456
    driver-class-name: org.postgresql.Driver
  config:
    name: HomeofeSportsRacingSimulatorSettings
server:
  port: 8080



